### PR TITLE
Fix parsing of escaped quotes

### PR DESCRIPTION
**Pull request by andreamk**
I have updated the regexes so that it executes a correct match in the case of quotas in the constant string.

For example
define ('DB_PASSWORD', "aaaa\\" aaaa ");
executed a wrong match

### CODE REVIEW

**Comment by schlessera** [comment]
@andreamk, can you add a test that demonstrates the faulty behavior and make sure that the test fails without the above change and then succeeds with the change? This way, we can make sure that:
- the fix is the correct one, and
- we won't reintroduce a regression for this later on.

**Comment by andreamk** [comment]
I will do it but I have to find the time.
For the moment I am attaching the screenshots of the regex online before and after my changes.

before

after

**Comment by schlessera** [comment]
@andreamk Just let me know if I should help out with adding the test.

**Comment by schlessera** [comment]
I added a quick set of tests to check for quotes within quotes.

**Comment by schlessera** [comment]
Thanks for the PR, @andreamk !

**Pull request merged**
