### PR TITLE
First pass at constant/variable transformation

### PR DESCRIPTION
**Pull request by fjarrett**
@danielbachhuber API here is pretty self-explanatory. So far it seems to work pretty well.

Going continue to poke at it and get a test framework in place so we can throw in a ton of scenarios.

Examples:

```php
$config_transformer = new WPConfigTransformer( '/path/to/wp-config.php' );
$config_transformer->exists( 'constant', 'DB_HOST' );              // Returns true
$config_transformer->add( 'constant', 'DB_HOST', 'localhost' );    // Returns false
$config_transformer->update( 'constant', 'DB_HOST', 'localhost' ); // Returns true
$config_transformer->remove( 'constant', 'DB_HOST' );              // Returns true
```

Examples using raw values:

```php
$config_transformer->update( 'constant', 'FS_CHMOD_DIR', '(0755 & ~ umask())', [ 'raw' => true ] );
$config_transformer->update( 'constant', 'ABSPATH', "dirname( __FILE__ ) . '/somewhere/else/'", [ 'raw' => true ] );
$config_transformer->update( 'constant', 'WP_DEBUG', 'true', [ 'raw' => true ] );
$config_transformer->update( 'constant', 'FOO', "array( 'baz', 'qux' )", [ 'raw' => true ] );
$config_transformer->update( 'constant', 'BAR', 'null', [ 'raw' => true ] );
```

Variables also work:

```php
$config_transformer->update( 'variable', 'table_prefix', 'wp_foo_' );
```

### CODE REVIEW

**Comment by danielbachhuber** [comment]
💯 so cool!

**Comment by fjarrett** [comment]
Added a bunch of thoughts to the [README](https://github.com/fjarrett/wp-config-transformer/blob/master/README.md) to explain how this all works.

**Comment by schlessera** [comment]
@fjarrett Looks great so far!

This will obviously need a robust set of unit tests to make sure we can rely on these changes to work across the board. You've mentioned in the description that you'll take care of tests as well, but feel free to ping me when you need help with anything!

**Comment by schlessera** [comment]
Travis is missing a `composer install` step. That's why you're getting the error that the `vendor/autoload.php` file is missing.

**Comment by fjarrett** [comment]
@schlessera OK I've thrown a bunch of test scenarios together. I found it difficult to find a simple testing pattern since we have to create actual files then include them to check their values and constants can only be defined once. As a result, things turned out a little more heavy-handed than I prefer, and I'm open to suggestions for simplifying the whole thing.

**Comment by schlessera** [comment]
@fjarrett Hehe, you went all out on that one, great job so far! 😄 

I'll probably only get around to doing a thorough review after new year's day, but here are already a few quick observations:

- You changed the license to GPLv2. The rest of WP-CLI is under the more permissive MIT license. As WP-CLI is meant to be a tool for companies with proprietary toolchains as well, I'd like to stay with the MIT license, so I will not bundle this changed library in case you feel strongly about the GPLv2 license. If you are unsure about the differences between MIT and GPLv2, just let me know so we can discuss.
- The short descriptions in the doc blocks should adhere to the [WPCS convention](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#language) of using the third person singular form.
- Right now, we're still at a PHP 5.3+ requirement. I think your code requires PHP 5.4+. Please change it to PHP 5.3+ requirement, otherwise, we cannot bundle it with the next version (1.5.0).
- The test data is inside of a `bin` folder. By convention, `bin` normally stands for `binary`, and contains the executable files of a project. A better name would be `fixtures`, for example.
- The file `wp-config-sample.php` gives the impression it would be a copy from the WP core files. However, the last line is commented out. I'd either rename the file to make it clear it is not a valid config file, or restore the last line.

If you have questions about any of the above, feel free to ask away or ping me on Slack!

**Comment by fjarrett** [comment]
Thanks @schlessera! First round of changes pushed based on your feedback.

**Comment by schlessera** [comment]
@fjarrett Looks good.
I think you misinterpreted my comment about the short description, though. If you click through the [link I provided to WPCS](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#language), you can see that it requires the third person singular form.

So, instead of this:
```
Apply formatting to a config value.
```
WPCS requires this:
```
Applies formatting to a config value.
```

You write the short description as if the sentence would start with the pronoun `it`, referring to the function/method:
```
[It] Applies formatting to a config value.
```

**Comment by fjarrett** [comment]
Travis is throwing `disk quota exceeded` errors - hoping that will clear up on its own...

**Comment by schlessera** [comment]
Seems to have been a temporary issue, a restart got us through successfully.

**Comment by schlessera** [comment]
Merging this as is so it can more easily be used and tested. Any improvements/fixes will be separate PRs.

**Comment by gitlost** [comment]
@schlessera so the thing to do here first is to review `wp-cli/wp-config-transformer` for bundling? Or has it been sufficiently reviewed and we just need to do a PR on `wp-cli/wp-cli` to bundle it?

(Am reviewing this PR anyway...)

**Comment by gitlost** [comment]
As it's just one file and phpunit tests I'm wondering if it wouldn't be best/simplest to merge `wp-cli/wp-config-transformer` into this repo.....?

**Comment by schlessera** [comment]
One of the original goals was to create a stand-alone library to deal with wp-config.php modifications, as having a WP-CLI command to do it is just one individual use case. There are other instances where such a library can be useful as well.

**Comment by gitlost** [comment]
Hmm, okay, but having all these separate repos is a logistical nightmare to be honest.

So this repo is reviewed and just needs to be bundled then?

(Unfortunately I'm very stuck for time today and won't get back to doing WP-CLI stuff until tonight.)

**Comment by gitlost** [comment]
Oh okay I see it's already released. And will be "bundled" with `config-command` as soon as https://github.com/wp-cli/config-command/pull/44 is merged.

So the only (but big) to-do item is to change `make-phar.php` to include it?

**Pull request merged**
